schema_version = "1.0.0"

id = "cab87_video_plane_tool"
name = "Cab87 Video Plane Tool"
version = "0.2.0"
tagline = "Create video planes and Resolve XML cut grids"
maintainer = "Cab87"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:MIT"]

tags = ["Import-Export", "Material", "Video"]
