local CameraConfig = {
	cameraMinSpeed = 25,
	cameraMinDistance = 22,
	cameraMinHeight = 12,
	cameraMinFov = 70,
	cameraMaxSpeed = 120,
	cameraMaxDistance = 12,
	cameraMaxHeight = 8,
	cameraMaxFov = 110,
	cameraLookHeight = 4.5,
	cameraLookAheadDistance = 8.0,
	cameraMovementDirectionMinSpeed = 6.0,
	cameraReverseLookDelay = 2.00,
	cameraYawResponsiveness = 4.0,
	cameraTargetResponsiveness = 18.0,
	cameraPositionResponsiveness = 25.0,
	cameraMaxDeltaTime = 0.050,
	cameraCrashShakeMinSpeed = 8,
	cameraCrashShakeMaxSpeed = 190,
	cameraLandingShakeMinSpeed = 45,
	cameraLandingShakeMaxSpeed = 135,
	cameraCrashShakeDuration = 0.60,
	cameraCrashShakeDistance = 2.4,
	cameraCrashShakeAngleDegrees = 2.2,
	cameraCrashShakeFrequency = 25,
	cameraCrashShakeCooldown = 0.20,
	cameraBoostShakeIntensity = 0.50,
}

return CameraConfig
