local roadSurfaceY = 0.52
local carRideHeight = 2.3

local Config = {
	cityBlocks = 7,
	blockSize = 192,
	roadWidth = 108,
	roadSurfaceY = roadSurfaceY,
	buildingInset = 14,
	buildingHeightMin = 25,
	buildingHeightMax = 120,

	carRideHeight = carRideHeight,
	carSpawn = Vector3.new(0, roadSurfaceY + carRideHeight, 0),
	carAccel = 95,
	carBrake = 130,
	carReverseDelay = 0.25,
	carReverseStopSpeed = 2,
	carDrag = 42,
	carMaxForward = 170,
	carMaxReverse = 55,
	carTurnRate = 2.5,
	carMinTurnSpeed = 8,
	carGrip = 14,
	carDriftGrip = 0.12,
	carDriftDrag = 6,
	carDriftRotationSensitivity = 2.45,
	carDriftAccelMultiplier = 0.35,
	carDriftDecel = 36,
	carDriftSlideForce = 20,
	carDriftMinSpeed = 35,
	carDriftLeanDegrees = 16,
	carDriftLeanFullSpeed = 95,
	carDriftLeanFollow = 9,
	carDriftBoostChargeTime = 0.8,
	carDriftBoostWindow = 1.25,
	carDriftBoostImpulse = 28,
	carDriftBoostAccel = 190,
	carDriftBoostDuration = 0.45,
	carDriftBoostMaxSpeed = 220,
	carCrashRadius = 7.5,
	carCrashHeightClearance = 3,
	carCrashBounce = 0.18,
	carCrashSlideRetain = 0.35,
	carWallScrapeMaxAngleDegrees = 30,
	carWallScrapeSpeedRetain = 0.93,
	carWallScrapeMinSpeed = 12,
	carWallScrapeYawRate = 8,
	carGravityUp = 110,
	carGravityDown = 215,
	carGroundSnapDistance = 3.5,
	carGroundProbeHalfWidth = 4.8,
	carGroundProbeHalfLength = 6.4,
	carGroundProbeHeight = 90,
	carGroundProbeDepth = 220,
	carMaxDeltaTime = 1 / 20,
	carPitchFollow = 8,
	carRollFollow = 8,
	carAirPitchScale = 220,
	carMaxPitchDegrees = 24,
	carGroundMaxRollDegrees = 24,

	driveInputRemoteName = "Cab87DriveInput",
	cameraEventRemoteName = "Cab87CameraEvent",
	cameraBaseDistance = 34,
	cameraFastDistance = 48,
	cameraHeight = 13,
	cameraLookHeight = 4.5,
	cameraLookAheadDistance = 8,
	cameraSpeedLookAheadDistance = 16,
	cameraBaseFov = 70,
	cameraFastFov = 86,
	cameraSpeedMin = 25,
	cameraSpeedMax = 170,
	cameraMovementDirectionMinSpeed = 6,
	cameraYawResponsiveness = 4,
	cameraTargetResponsiveness = 18,
	cameraPositionResponsiveness = 9,
	cameraDistanceResponsiveness = 7,
	cameraFovResponsiveness = 6,
	cameraMaxDeltaTime = 1 / 20,
	cameraCrashShakeMinSpeed = 8,
	cameraCrashShakeMaxSpeed = 145,
	cameraCrashShakeDuration = 0.36,
	cameraCrashShakeDistance = 2.4,
	cameraCrashShakeAngleDegrees = 2.2,
	cameraCrashShakeFrequency = 25,
	cameraCrashShakeCooldown = 0.18,
	debugTuneRemoteName = "Cab87DebugTune",
	debugPanelEnabled = true,
	debugPanelStudioOnly = true,
	debugTuningProperties = {
		{ key = "carAccel", label = "Accel", min = 0, max = 250, step = 5 },
		{ key = "carBrake", label = "Brake", min = 0, max = 300, step = 5 },
		{ key = "carReverseDelay", label = "Reverse Delay", min = 0, max = 1, step = 0.05 },
		{ key = "carReverseStopSpeed", label = "Reverse Stop", min = 0, max = 12, step = 0.25 },
		{ key = "carDrag", label = "Drag", min = 0, max = 120, step = 1 },
		{ key = "carMaxForward", label = "Max Forward", min = 20, max = 320, step = 5 },
		{ key = "carMaxReverse", label = "Max Reverse", min = 0, max = 140, step = 5 },
		{ key = "carTurnRate", label = "Turn Rate", min = 0, max = 8, step = 0.05 },
		{ key = "carMinTurnSpeed", label = "Min Turn Speed", min = 0, max = 60, step = 1 },
		{ key = "carGrip", label = "Grip", min = 0, max = 40, step = 0.25 },
		{ key = "carDriftGrip", label = "Drift Grip", min = 0, max = 4, step = 0.01 },
		{ key = "carDriftDrag", label = "Drift Drag", min = 0, max = 80, step = 1 },
		{ key = "carDriftRotationSensitivity", label = "Drift Rotation", min = 0.1, max = 8, step = 0.05 },
		{ key = "carDriftAccelMultiplier", label = "Drift Accel", min = 0, max = 1, step = 0.01 },
		{ key = "carDriftDecel", label = "Drift Decel", min = 0, max = 160, step = 1 },
		{ key = "carDriftSlideForce", label = "Drift Slide", min = 0, max = 120, step = 1 },
		{ key = "carDriftMinSpeed", label = "Drift Min Speed", min = 0, max = 120, step = 1 },
		{ key = "carDriftLeanDegrees", label = "Drift Lean", min = -35, max = 35, step = 1 },
		{ key = "carDriftLeanFullSpeed", label = "Drift Lean Speed", min = 1, max = 220, step = 5 },
		{ key = "carDriftLeanFollow", label = "Drift Lean Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carDriftBoostChargeTime", label = "Boost Charge", min = 0, max = 3, step = 0.05 },
		{ key = "carDriftBoostWindow", label = "Boost Window", min = 0, max = 4, step = 0.05 },
		{ key = "carDriftBoostImpulse", label = "Boost Impulse", min = 0, max = 100, step = 1 },
		{ key = "carDriftBoostAccel", label = "Boost Accel", min = 0, max = 400, step = 5 },
		{ key = "carDriftBoostDuration", label = "Boost Duration", min = 0, max = 2, step = 0.05 },
		{ key = "carDriftBoostMaxSpeed", label = "Boost Max Speed", min = 20, max = 360, step = 5 },
		{ key = "carCrashBounce", label = "Crash Bounce", min = 0, max = 1, step = 0.01 },
		{ key = "carCrashSlideRetain", label = "Crash Slide", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeMaxAngleDegrees", label = "Wall Scrape Angle", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeSpeedRetain", label = "Wall Scrape Speed", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeMinSpeed", label = "Wall Scrape Min", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeYawRate", label = "Wall Scrape Turn", min = 0, max = 24, step = 0.5 },
		{ key = "carGravityUp", label = "Gravity Up", min = 20, max = 320, step = 5 },
		{ key = "carGravityDown", label = "Gravity Down", min = 20, max = 520, step = 5 },
		{ key = "carGroundSnapDistance", label = "Ground Snap", min = 0, max = 12, step = 0.25 },
		{ key = "carGroundProbeHalfWidth", label = "Probe Width", min = 1, max = 8, step = 0.1 },
		{ key = "carGroundProbeHalfLength", label = "Probe Length", min = 2, max = 10, step = 0.1 },
		{ key = "carPitchFollow", label = "Pitch Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carRollFollow", label = "Roll Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carMaxPitchDegrees", label = "Max Pitch", min = 0, max = 45, step = 1 },
		{ key = "carGroundMaxRollDegrees", label = "Max Roll", min = 0, max = 45, step = 1 },
		{ key = "cameraBaseDistance", label = "Camera Base Dist", min = 12, max = 80, step = 1 },
		{ key = "cameraFastDistance", label = "Camera Fast Dist", min = 12, max = 100, step = 1 },
		{ key = "cameraHeight", label = "Camera Height", min = 3, max = 40, step = 0.5 },
		{ key = "cameraLookHeight", label = "Camera Look Height", min = 0, max = 18, step = 0.25 },
		{ key = "cameraLookAheadDistance", label = "Camera Look Ahead", min = 0, max = 40, step = 1 },
		{ key = "cameraSpeedLookAheadDistance", label = "Camera Speed Look", min = 0, max = 60, step = 1 },
		{ key = "cameraBaseFov", label = "Camera Base FOV", min = 40, max = 100, step = 1 },
		{ key = "cameraFastFov", label = "Camera Fast FOV", min = 40, max = 110, step = 1 },
		{ key = "cameraSpeedMin", label = "Camera Speed Min", min = 0, max = 220, step = 5 },
		{ key = "cameraSpeedMax", label = "Camera Speed Max", min = 0, max = 320, step = 5 },
		{ key = "cameraMovementDirectionMinSpeed", label = "Camera Move Dir Min", min = 0, max = 50, step = 1 },
		{ key = "cameraYawResponsiveness", label = "Camera Yaw Return", min = 0, max = 18, step = 0.25 },
		{ key = "cameraTargetResponsiveness", label = "Camera Target Follow", min = 0, max = 60, step = 0.5 },
		{ key = "cameraPositionResponsiveness", label = "Camera Follow", min = 0, max = 24, step = 0.5 },
		{ key = "cameraDistanceResponsiveness", label = "Camera Zoom Follow", min = 0, max = 24, step = 0.5 },
		{ key = "cameraFovResponsiveness", label = "Camera FOV Follow", min = 0, max = 24, step = 0.5 },
		{ key = "cameraMaxDeltaTime", label = "Camera Max Dt", min = 0.008, max = 0.2, step = 0.001 },
		{ key = "cameraCrashShakeMinSpeed", label = "Camera Shake Min", min = 0, max = 120, step = 5 },
		{ key = "cameraCrashShakeMaxSpeed", label = "Camera Shake Max", min = 0, max = 260, step = 5 },
		{ key = "cameraCrashShakeDuration", label = "Camera Shake Time", min = 0, max = 1.5, step = 0.02 },
		{ key = "cameraCrashShakeDistance", label = "Camera Shake Dist", min = 0, max = 8, step = 0.1 },
		{ key = "cameraCrashShakeAngleDegrees", label = "Camera Shake Angle", min = 0, max = 10, step = 0.1 },
		{ key = "cameraCrashShakeFrequency", label = "Camera Shake Freq", min = 1, max = 60, step = 1 },
		{ key = "cameraCrashShakeCooldown", label = "Camera Shake Cool", min = 0, max = 1, step = 0.02 },
	},

	rampRun = 64,
	rampHeight = 18,
	rampWidth = 44,
	rampThickness = 2,
	stuntPlatformHeight = 3,
	stuntPlatformLength = 100,
	stuntPlatformWidth = 56,
	stuntPlatformGap = 80,
}

return Config
