local roadSurfaceY = 0.52
local carRideHeight = 2.3

local Config = {
	cityBlocks = 7,
	blockSize = 192,
	roadWidth = 108,
	roadSurfaceY = roadSurfaceY,
	buildingInset = 14,
	buildingHeightMin = 25,
	buildingHeightMax = 120,

	-- Map generation V2 (chunk 1): arterial-first roads + Voronoi-style districts.
	districtCount = 9,
	districtJitter = 0.35,
	arterialRingRadiusBlocks = 4,
	arterialSpineOffsetBlocks = 3,
	secondaryRoadEveryBlocks = 2,
	secondaryRoadChance = 0.55,

	carRideHeight = carRideHeight,
	carSpawn = Vector3.new(0, roadSurfaceY + carRideHeight, 0),
	carServerPivotValueName = "Cab87ServerPivot",
	carVisualResponsiveness = 26,
	carVisualSnapDistance = 45,
	carAccel = 95,
	carBrake = 130,
	carReverseDelay = 0.25,
	carReverseStopSpeed = 2,
	carDrag = 42,
	carMaxForward = 170,
	carMaxReverse = 55,
	carTurnRate = 1.3,
	carMinTurnSpeed = 8,
	carTurnSpeedAtMinSpeed = 1,
	carTurnSpeedAtMaxSpeed = 0.35,
	carGrip = 3,
	carDriftGrip = 1,
	carDriftDrag = 6,
	carDriftRotationSensitivity = 2,
	carDriftAccelMultiplier = 0.35,
	carDriftDecel = 36,
	carDriftSlideForce = 20,
	carDriftMinSpeed = 35,
	carDriftLeanDegrees = 16,
	carDriftLeanFullSpeed = 95,
	carDriftLeanFollow = 9,
	carDriftBoostChargeTime = 0.8,
	carDriftBoostWindow = 1.25,
	carDriftBoostImpulse = 28,
	carDriftBoostAccel = 190,
	carDriftBoostDuration = 0.45,
	carDriftBoostMaxSpeed = 220,
	carCrashRadius = 7.5,
	carCrashHeightClearance = 3,
	carCrashBounce = 0.6,
	carCrashSlideRetain = 0.5,
	carWallScrapeMaxAngleDegrees = 30,
	carWallScrapeSpeedRetain = 0.8,
	carWallScrapeDeflectAngleDegrees = 12,
	carWallScrapeMinSpeed = 12,
	carWallScrapeYawRate = 8,
	carGravityUp = 80,
	carGravityDown = 330,
	carGroundSnapDistance = 3.5,
	carGroundProbeHalfWidth = 4.8,
	carGroundProbeHalfLength = 6.4,
	carGroundProbeHeight = 90,
	carGroundProbeDepth = 220,
	carMaxDeltaTime = 1 / 20,
	carPitchFollow = 8,
	carRollFollow = 8,
	carAirPitchInputDegrees = 18,
	carAirRollInputDegrees = 18,
	carAirRotationFollow = 7,
	carMaxPitchDegrees = 24,
	carGroundMaxRollDegrees = 24,
	carLandingBoostImpulse = 24,
	carLandingBoostMaxSpeed = 220,
	carLandingBoostAlignDegrees = 10,
	carBoostWheelieDegrees = 10,
	carBoostWheelieDuration = 0.35,
	carBoostWheelieFollow = 16,

	driveInputRemoteName = "Cab87DriveInput",
	cameraEventRemoteName = "Cab87CameraEvent",
	cameraMinSpeed = 25,
	cameraMinDistance = 34,
	cameraMinHeight = 13,
	cameraMinFov = 70,
	cameraMaxSpeed = 170,
	cameraMaxDistance = 48,
	cameraMaxHeight = 13,
	cameraMaxFov = 86,
	cameraLookHeight = 4.5,
	cameraLookAheadDistance = 8,
	cameraMovementDirectionMinSpeed = 6,
	cameraReverseLookDelay = 0.6,
	cameraYawResponsiveness = 4,
	cameraTargetResponsiveness = 18,
	cameraPositionResponsiveness = 9,
	cameraMaxDeltaTime = 1 / 20,
	cameraCrashShakeMinSpeed = 8,
	cameraCrashShakeMaxSpeed = 145,
	cameraLandingShakeMinSpeed = 45,
	cameraLandingShakeMaxSpeed = 135,
	cameraCrashShakeDuration = 0.36,
	cameraCrashShakeDistance = 2.4,
	cameraCrashShakeAngleDegrees = 2.2,
	cameraCrashShakeFrequency = 25,
	cameraCrashShakeCooldown = 0.18,
	cameraBoostShakeIntensity = 0.35,
	debugTuneRemoteName = "Cab87DebugTune",
	debugPanelEnabled = true,
	debugPanelStudioOnly = true,
	debugTuningProperties = {
		{ key = "carVisualResponsiveness", label = "Cab Visual Follow", min = 0, max = 80, step = 1 },
		{ key = "carVisualSnapDistance", label = "Cab Visual Snap", min = 1, max = 200, step = 5 },
		{ key = "carAccel", label = "Accel", min = 0, max = 250, step = 5 },
		{ key = "carBrake", label = "Brake", min = 0, max = 300, step = 5 },
		{ key = "carReverseDelay", label = "Reverse Delay", min = 0, max = 1, step = 0.05 },
		{ key = "carReverseStopSpeed", label = "Reverse Stop", min = 0, max = 12, step = 0.25 },
		{ key = "carDrag", label = "Drag", min = 0, max = 120, step = 1 },
		{ key = "carMaxForward", label = "Max Forward", min = 20, max = 320, step = 5 },
		{ key = "carMaxReverse", label = "Max Reverse", min = 0, max = 140, step = 5 },
		{ key = "carTurnRate", label = "Turn Rate", min = 0, max = 8, step = 0.05 },
		{ key = "carMinTurnSpeed", label = "Min Turn Speed", min = 0, max = 60, step = 1 },
		{ key = "carTurnSpeedAtMinSpeed", label = "Turn @ Min Speed", min = 0, max = 2, step = 0.05 },
		{ key = "carTurnSpeedAtMaxSpeed", label = "Turn @ Max Speed", min = 0, max = 2, step = 0.05 },
		{ key = "carGrip", label = "Grip", min = 0, max = 40, step = 0.25 },
		{ key = "carDriftGrip", label = "Drift Grip", min = 0, max = 4, step = 0.01 },
		{ key = "carDriftDrag", label = "Drift Drag", min = 0, max = 80, step = 1 },
		{ key = "carDriftRotationSensitivity", label = "Drift Rotation", min = 0.1, max = 8, step = 0.05 },
		{ key = "carDriftAccelMultiplier", label = "Drift Accel", min = 0, max = 1, step = 0.01 },
		{ key = "carDriftDecel", label = "Drift Decel", min = 0, max = 160, step = 1 },
		{ key = "carDriftSlideForce", label = "Drift Slide", min = 0, max = 120, step = 1 },
		{ key = "carDriftMinSpeed", label = "Drift Min Speed", min = 0, max = 120, step = 1 },
		{ key = "carDriftLeanDegrees", label = "Drift Lean", min = -35, max = 35, step = 1 },
		{ key = "carDriftLeanFullSpeed", label = "Drift Lean Speed", min = 1, max = 220, step = 5 },
		{ key = "carDriftLeanFollow", label = "Drift Lean Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carDriftBoostChargeTime", label = "Boost Charge", min = 0, max = 3, step = 0.05 },
		{ key = "carDriftBoostWindow", label = "Boost Window", min = 0, max = 4, step = 0.05 },
		{ key = "carDriftBoostImpulse", label = "Boost Impulse", min = 0, max = 100, step = 1 },
		{ key = "carDriftBoostAccel", label = "Boost Accel", min = 0, max = 400, step = 5 },
		{ key = "carDriftBoostDuration", label = "Boost Duration", min = 0, max = 2, step = 0.05 },
		{ key = "carDriftBoostMaxSpeed", label = "Boost Max Speed", min = 20, max = 360, step = 5 },
		{ key = "carCrashBounce", label = "Crash Bounce", min = 0, max = 1, step = 0.01 },
		{ key = "carCrashSlideRetain", label = "Crash Slide", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeMaxAngleDegrees", label = "Wall Scrape Angle", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeSpeedRetain", label = "Wall Scrape Speed", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeDeflectAngleDegrees", label = "Wall Scrape Deflect", min = 0, max = 45, step = 1 },
		{ key = "carWallScrapeMinSpeed", label = "Wall Scrape Min", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeYawRate", label = "Wall Scrape Turn", min = 0, max = 24, step = 0.5 },
		{ key = "carGravityUp", label = "Gravity Up", min = 20, max = 320, step = 5 },
		{ key = "carGravityDown", label = "Gravity Down", min = 20, max = 520, step = 5 },
		{ key = "carGroundSnapDistance", label = "Ground Snap", min = 0, max = 12, step = 0.25 },
		{ key = "carGroundProbeHalfWidth", label = "Probe Width", min = 1, max = 8, step = 0.1 },
		{ key = "carGroundProbeHalfLength", label = "Probe Length", min = 2, max = 10, step = 0.1 },
		{ key = "carPitchFollow", label = "Pitch Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carRollFollow", label = "Roll Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carAirPitchInputDegrees", label = "Air Pitch Input", min = -45, max = 45, step = 1 },
		{ key = "carAirRollInputDegrees", label = "Air Roll Input", min = -45, max = 45, step = 1 },
		{ key = "carAirRotationFollow", label = "Air Rotation Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carMaxPitchDegrees", label = "Max Pitch", min = 0, max = 45, step = 1 },
		{ key = "carGroundMaxRollDegrees", label = "Max Roll", min = 0, max = 45, step = 1 },
		{ key = "carLandingBoostImpulse", label = "Landing Boost", min = 0, max = 120, step = 1 },
		{ key = "carLandingBoostMaxSpeed", label = "Landing Boost Max", min = 20, max = 360, step = 5 },
		{ key = "carLandingBoostAlignDegrees", label = "Landing Boost Align", min = 0, max = 35, step = 1 },
		{ key = "carBoostWheelieDegrees", label = "Boost Wheelie", min = 0, max = 35, step = 1 },
		{ key = "carBoostWheelieDuration", label = "Boost Wheelie Time", min = 0, max = 2, step = 0.05 },
		{ key = "carBoostWheelieFollow", label = "Boost Wheelie Follow", min = 0, max = 40, step = 0.5 },
		{ key = "cameraMinSpeed", label = "Camera Min Speed", min = 0, max = 220, step = 5 },
		{ key = "cameraMinDistance", label = "Camera Min Dist", min = 1, max = 100, step = 1 },
		{ key = "cameraMinHeight", label = "Camera Min Height", min = 1, max = 60, step = 0.5 },
		{ key = "cameraMinFov", label = "Camera Min FOV", min = 40, max = 110, step = 1 },
		{ key = "cameraMaxSpeed", label = "Camera Max Speed", min = 0, max = 320, step = 5 },
		{ key = "cameraMaxDistance", label = "Camera Max Dist", min = 1, max = 120, step = 1 },
		{ key = "cameraMaxHeight", label = "Camera Max Height", min = 1, max = 60, step = 0.5 },
		{ key = "cameraMaxFov", label = "Camera Max FOV", min = 40, max = 120, step = 1 },
		{ key = "cameraReverseLookDelay", label = "Reverse Look Delay", min = 0, max = 2, step = 0.05 },
		{ key = "cameraBoostShakeIntensity", label = "Boost Shake", min = 0, max = 1, step = 0.01 },
	},

	rampRun = 64,
	rampHeight = 18,
	rampWidth = 44,
	rampThickness = 2,
	stuntPlatformHeight = 3,
	stuntPlatformLength = 100,
	stuntPlatformWidth = 56,
	stuntPlatformGap = 80,
}

return Config
