local roadSurfaceY = 0.52
local carRideHeight = 2.3

local Config = {
	cityBlocks = 7,
	blockSize = 192,
	roadWidth = 108,
	roadSurfaceY = roadSurfaceY,
	buildingInset = 14,
	buildingHeightMin = 25,
	buildingHeightMax = 120,

	-- Map generation V2 (chunk 1): arterial-first roads + Voronoi-style districts.
	districtCount = 9,
	districtJitter = 0.35,
	arterialRingRadiusBlocks = 4,
	arterialSpineOffsetBlocks = 3,
	secondaryRoadEveryBlocks = 3,
	secondaryRoadChance = 0.35,

	useAuthoredRoadEditorWorld = true,
	authoredRoadCollisionWidth = 28,
	authoredRoadCollisionThickness = 0.2,
	authoredRoadCollisionSurfaceOffset = 0.6,
	authoredRoadSampleStepStuds = 8,
	authoredRoadOverlap = 1.0,

	carRideHeight = carRideHeight,
	carSpawn = Vector3.new(0, roadSurfaceY + carRideHeight, 0),
	carServerPivotValueName = "Cab87ServerPivot",
	carVisualDriftingAttribute = "Cab87VisualDrifting",
	carVisualDriftBoostReadyAttribute = "Cab87VisualDriftBoostReady",
	carVisualBoostPulseAttribute = "Cab87VisualBoostPulse",
	carVisualLandingPulseAttribute = "Cab87VisualLandingPulse",
	carVisualLandingSpeedAttribute = "Cab87VisualLandingSpeed",
	carSpeedAttribute = "Cab87Speed",
	carVisualResponsiveness = 26,
	carVisualSnapDistance = 46,
	carVisualInterpolationDelay = 0.08,
	carVisualMaxExtrapolationTime = 0.10,
	carBodySpringPitchDegrees = 7,
	carBodySpringRollDegrees = 4,
	carBodySpringYawDegrees = 2,
	carBodySpringAccelForFullTilt = 95,
	carBodySpringFrequency = 2.6,
	carBodySpringDamping = 0.52,
	carAccel = 95,
	carBrake = 80,
	carReverseDelay = 0.5,
	carReverseStopSpeed = 2,
	carDrag = 42,
	carMaxForward = 120,
	carMaxReverse = 55,
	carTurnRate = 2.0,
	carMinTurnSpeed = 8,
	carTurnSpeedAtMinSpeed = 1.0,
	carTurnSpeedAtMaxSpeed = 0.7,
	carGrip = 3,
	carDriftGrip = 1,
	carDriftDrag = 6,
	carDriftRotationSensitivity = 2,
	carDriftAccelMultiplier = 0.35,
	carDriftDecel = 36,
	carDriftSlideForce = 20,
	carDriftMinSpeed = 35,
	carDriftLeanDegrees = 16,
	carDriftLeanFullSpeed = 96,
	carDriftLeanFollow = 9,
	carDriveLeanDegrees = 8,
	carDriveLeanMinSpeed = 8,
	carDriveLeanFullSpeed = 106,
	carDriveLeanFollow = 8,
	carDriftBoostChargeTime = 0.8,
	carDriftBoostWindow = 1.25,
	carDriftBoostImpulse = 28,
	carDriftBoostAccel = 190,
	carDriftBoostDuration = 0.45,
	carDriftBoostMaxSpeed = 220,
	carCrashRadius = 7.5,
	carCrashHeightClearance = 3,
	carCrashBounce = 0.6,
	carCrashSlideRetain = 0.5,
	carWallScrapeMaxAngleDegrees = 30,
	carWallScrapeSpeedRetain = 0.8,
	carWallScrapeDeflectAngleDegrees = 12,
	carWallScrapeMinSpeed = 12,
	carWallScrapeYawRate = 8,
	carGravityUp = 80,
	carGravityDown = 330,
	carGroundSnapDistance = 3.5,
	carGroundMaxStepUp = 4.0,
	carGroundProbeHalfWidth = 4.8,
	carGroundProbeHalfLength = 6.4,
	carGroundProbeHeight = 90,
	carGroundProbeDepth = 220,
	carFallResetY = roadSurfaceY - 80,
	carFallResetLookbackTime = 1,
	carFallResetTurnaroundDegrees = 180,
	carFallResetMinGroundContacts = 4,
	carFallResetCooldown = 0.5,
	carMaxDeltaTime = 1 / 20,
	carPitchFollow = 24,
	carRollFollow = 24,
	carAirPitchInputDegrees = 75,
	carAirRollInputDegrees = 90,
	carAirRotationFollow = 7,
	carAirPitchUpGravityMultiplier = 0.75,
	carAirPitchDownGravityMultiplier = 1.45,
	carMaxPitchDegrees = 75,
	carGroundMaxRollDegrees = 75,
	carLandingBoostImpulse = 24,
	carLandingBoostMaxSpeed = 220,
	carLandingBoostAlignDegrees = 10,
	carBoostWheelieDegrees = 35,
	carBoostWheelieDuration = 1.00,
	carBoostWheelieReturnDuration = 0.50,
	carBoostWheelieFollow = 16,
	carLandingBounceMinSpeed = 30,
	carLandingBounceMaxSpeed = 150,
	carLandingBounceImpulse = 27,
	carLandingBounceSpring = 70,
	carLandingBounceDamping = 12.0,
	carLandingBounceMaxOffset = 1.8,

	driveInputRemoteName = "Cab87DriveInput",
	cameraEventRemoteName = "Cab87CameraEvent",
	cameraMinSpeed = 25,
	cameraMinDistance = 34,
	cameraMinHeight = 13.0,
	cameraMinFov = 70,
	cameraMaxSpeed = 120,
	cameraMaxDistance = 12,
	cameraMaxHeight = 8.5,
	cameraMaxFov = 110,
	cameraLookHeight = 4.5,
	cameraLookAheadDistance = 8.0,
	cameraMovementDirectionMinSpeed = 6.0,
	cameraReverseLookDelay = 2.00,
	cameraYawResponsiveness = 4.0,
	cameraTargetResponsiveness = 18.0,
	cameraPositionResponsiveness = 25.0,
	cameraMaxDeltaTime = 0.050,
	cameraCrashShakeMinSpeed = 8,
	cameraCrashShakeMaxSpeed = 190,
	cameraLandingShakeMinSpeed = 45,
	cameraLandingShakeMaxSpeed = 135,
	cameraCrashShakeDuration = 0.60,
	cameraCrashShakeDistance = 2.4,
	cameraCrashShakeAngleDegrees = 2.2,
	cameraCrashShakeFrequency = 25,
	cameraCrashShakeCooldown = 0.20,
	cameraBoostShakeIntensity = 0.50,
	debugTuneRemoteName = "Cab87DebugTune",
	debugPanelEnabled = true,
	debugPanelStudioOnly = true,
	debugTuningProperties = {
		{ key = "carVisualResponsiveness", label = "Cab Visual Follow", min = 0, max = 80, step = 1 },
		{ key = "carVisualSnapDistance", label = "Cab Visual Snap", min = 1, max = 200, step = 5 },
		{ key = "carVisualInterpolationDelay", label = "Cab Visual Delay", min = 0, max = 0.25, step = 0.005 },
		{ key = "carVisualMaxExtrapolationTime", label = "Cab Visual Predict", min = 0, max = 0.25, step = 0.005 },
		{ key = "carBodySpringPitchDegrees", label = "Body Spring Pitch", min = 0, max = 20, step = 0.5 },
		{ key = "carBodySpringRollDegrees", label = "Body Spring Roll", min = 0, max = 16, step = 0.5 },
		{ key = "carBodySpringYawDegrees", label = "Body Spring Yaw", min = 0, max = 8, step = 0.25 },
		{ key = "carBodySpringAccelForFullTilt", label = "Body Spring Accel", min = 10, max = 240, step = 5 },
		{ key = "carBodySpringFrequency", label = "Body Spring Freq", min = 0.5, max = 8, step = 0.1 },
		{ key = "carBodySpringDamping", label = "Body Spring Damp", min = 0.1, max = 2, step = 0.05 },
		{ key = "carAccel", label = "Accel", min = 0, max = 250, step = 5 },
		{ key = "carBrake", label = "Brake", min = 0, max = 300, step = 5 },
		{ key = "carReverseDelay", label = "Reverse Delay", min = 0, max = 1, step = 0.05 },
		{ key = "carReverseStopSpeed", label = "Reverse Stop", min = 0, max = 12, step = 0.25 },
		{ key = "carDrag", label = "Drag", min = 0, max = 120, step = 1 },
		{ key = "carMaxForward", label = "Max Forward", min = 20, max = 320, step = 5 },
		{ key = "carMaxReverse", label = "Max Reverse", min = 0, max = 140, step = 5 },
		{ key = "carTurnRate", label = "Turn Rate", min = 0, max = 8, step = 0.05 },
		{ key = "carMinTurnSpeed", label = "Min Turn Speed", min = 0, max = 60, step = 1 },
		{ key = "carTurnSpeedAtMinSpeed", label = "Turn @ Min Speed", min = 0, max = 2, step = 0.05 },
		{ key = "carTurnSpeedAtMaxSpeed", label = "Turn @ Max Speed", min = 0, max = 2, step = 0.05 },
		{ key = "carGrip", label = "Grip", min = 0, max = 40, step = 0.25 },
		{ key = "carDriftGrip", label = "Drift Grip", min = 0, max = 4, step = 0.01 },
		{ key = "carDriftDrag", label = "Drift Drag", min = 0, max = 80, step = 1 },
		{ key = "carDriftRotationSensitivity", label = "Drift Rotation", min = 0.1, max = 8, step = 0.05 },
		{ key = "carDriftAccelMultiplier", label = "Drift Accel", min = 0, max = 1, step = 0.01 },
		{ key = "carDriftDecel", label = "Drift Decel", min = 0, max = 160, step = 1 },
		{ key = "carDriftSlideForce", label = "Drift Slide", min = 0, max = 120, step = 1 },
		{ key = "carDriftMinSpeed", label = "Drift Min Speed", min = 0, max = 120, step = 1 },
		{ key = "carDriftLeanDegrees", label = "Drift Lean", min = -35, max = 35, step = 1 },
		{ key = "carDriftLeanFullSpeed", label = "Drift Lean Speed", min = 1, max = 220, step = 5 },
		{ key = "carDriftLeanFollow", label = "Drift Lean Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carDriveLeanDegrees", label = "Drive Lean", min = -35, max = 35, step = 1 },
		{ key = "carDriveLeanMinSpeed", label = "Drive Lean Min", min = 0, max = 120, step = 1 },
		{ key = "carDriveLeanFullSpeed", label = "Drive Lean Speed", min = 1, max = 220, step = 5 },
		{ key = "carDriveLeanFollow", label = "Drive Lean Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carDriftBoostChargeTime", label = "Boost Charge", min = 0, max = 3, step = 0.05 },
		{ key = "carDriftBoostWindow", label = "Boost Window", min = 0, max = 4, step = 0.05 },
		{ key = "carDriftBoostImpulse", label = "Boost Impulse", min = 0, max = 100, step = 1 },
		{ key = "carDriftBoostAccel", label = "Boost Accel", min = 0, max = 400, step = 5 },
		{ key = "carDriftBoostDuration", label = "Boost Duration", min = 0, max = 2, step = 0.05 },
		{ key = "carDriftBoostMaxSpeed", label = "Boost Max Speed", min = 20, max = 360, step = 5 },
		{ key = "carCrashBounce", label = "Crash Bounce", min = 0, max = 1, step = 0.01 },
		{ key = "carCrashSlideRetain", label = "Crash Slide", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeMaxAngleDegrees", label = "Wall Scrape Angle", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeSpeedRetain", label = "Wall Scrape Speed", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeDeflectAngleDegrees", label = "Wall Scrape Deflect", min = 0, max = 45, step = 1 },
		{ key = "carWallScrapeMinSpeed", label = "Wall Scrape Min", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeYawRate", label = "Wall Scrape Turn", min = 0, max = 24, step = 0.5 },
		{ key = "carGravityUp", label = "Gravity Up", min = 20, max = 320, step = 5 },
		{ key = "carGravityDown", label = "Gravity Down", min = 20, max = 520, step = 5 },
		{ key = "carGroundSnapDistance", label = "Ground Snap", min = 0, max = 12, step = 0.25 },
		{ key = "carGroundMaxStepUp", label = "Ground Step Up", min = 0, max = 12, step = 0.25 },
		{ key = "carGroundProbeHalfWidth", label = "Probe Width", min = 1, max = 8, step = 0.1 },
		{ key = "carGroundProbeHalfLength", label = "Probe Length", min = 2, max = 10, step = 0.1 },
		{ key = "carFallResetY", label = "Fall Reset Y", min = -500, max = 0, step = 5 },
		{ key = "carFallResetLookbackTime", label = "Fall Reset Lookback", min = 0, max = 3, step = 0.05 },
		{ key = "carFallResetTurnaroundDegrees", label = "Fall Reset Turn", min = 0, max = 360, step = 5 },
		{ key = "carFallResetMinGroundContacts", label = "Fall Reset Contacts", min = 1, max = 4, step = 1 },
		{ key = "carFallResetCooldown", label = "Fall Reset Cooldown", min = 0, max = 3, step = 0.05 },
		{ key = "carPitchFollow", label = "Pitch Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carRollFollow", label = "Roll Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carAirPitchInputDegrees", label = "Air Pitch Rate", min = -180, max = 180, step = 5 },
		{ key = "carAirRollInputDegrees", label = "Air Roll Rate", min = -180, max = 180, step = 5 },
		{ key = "carAirRotationFollow", label = "Air Rotation Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carAirPitchUpGravityMultiplier", label = "Air Nose Up Gravity", min = 0, max = 3, step = 0.05 },
		{ key = "carAirPitchDownGravityMultiplier", label = "Air Nose Down Gravity", min = 0, max = 3, step = 0.05 },
		{ key = "carMaxPitchDegrees", label = "Max Pitch", min = 0, max = 90, step = 1 },
		{ key = "carGroundMaxRollDegrees", label = "Max Roll", min = 0, max = 90, step = 1 },
		{ key = "carLandingBoostImpulse", label = "Landing Boost", min = 0, max = 120, step = 1 },
		{ key = "carLandingBoostMaxSpeed", label = "Landing Boost Max", min = 20, max = 360, step = 5 },
		{ key = "carLandingBoostAlignDegrees", label = "Landing Boost Align", min = 0, max = 35, step = 1 },
		{ key = "carBoostWheelieDegrees", label = "Boost Wheelie", min = 0, max = 35, step = 1 },
		{ key = "carBoostWheelieDuration", label = "Boost Wheelie Time", min = 0, max = 2, step = 0.05 },
		{ key = "carBoostWheelieReturnDuration", label = "Wheelie Return Time", min = 0, max = 2, step = 0.05 },
		{ key = "carBoostWheelieFollow", label = "Wheelie Rise Follow", min = 0, max = 40, step = 0.5 },
		{ key = "carLandingBounceMinSpeed", label = "Bounce Min Speed", min = 0, max = 160, step = 1 },
		{ key = "carLandingBounceMaxSpeed", label = "Bounce Max Speed", min = 0, max = 260, step = 5 },
		{ key = "carLandingBounceImpulse", label = "Bounce Impulse", min = 0, max = 60, step = 1 },
		{ key = "carLandingBounceSpring", label = "Bounce Spring", min = 0, max = 180, step = 5 },
		{ key = "carLandingBounceDamping", label = "Bounce Damping", min = 0, max = 50, step = 0.5 },
		{ key = "carLandingBounceMaxOffset", label = "Bounce Max Offset", min = 0, max = 6, step = 0.1 },
		{ key = "cameraMinSpeed", label = "Camera Min Speed", min = 0, max = 220, step = 5 },
		{ key = "cameraMinDistance", label = "Camera Min Dist", min = 1, max = 100, step = 1 },
		{ key = "cameraMinHeight", label = "Camera Min Height", min = 1, max = 60, step = 0.5 },
		{ key = "cameraMinFov", label = "Camera Min FOV", min = 40, max = 110, step = 1 },
		{ key = "cameraMaxSpeed", label = "Camera Max Speed", min = 0, max = 320, step = 5 },
		{ key = "cameraMaxDistance", label = "Camera Max Dist", min = 1, max = 120, step = 1 },
		{ key = "cameraMaxHeight", label = "Camera Max Height", min = 1, max = 60, step = 0.5 },
		{ key = "cameraMaxFov", label = "Camera Max FOV", min = 40, max = 120, step = 1 },
		{ key = "cameraLookHeight", label = "Camera Look Height", min = 0, max = 20, step = 0.25 },
		{ key = "cameraLookAheadDistance", label = "Camera Look Ahead", min = 0, max = 40, step = 0.5 },
		{ key = "cameraMovementDirectionMinSpeed", label = "Camera Move Dir Speed", min = 0, max = 40, step = 0.5 },
		{ key = "cameraReverseLookDelay", label = "Reverse Look Delay", min = 0, max = 2, step = 0.05 },
		{ key = "cameraYawResponsiveness", label = "Camera Yaw Follow", min = 0, max = 30, step = 0.5 },
		{ key = "cameraTargetResponsiveness", label = "Camera Target Follow", min = 0, max = 40, step = 0.5 },
		{ key = "cameraPositionResponsiveness", label = "Camera Pos Follow", min = 0, max = 40, step = 0.5 },
		{ key = "cameraMaxDeltaTime", label = "Camera Max Dt", min = 0.005, max = 0.2, step = 0.005 },
		{ key = "cameraCrashShakeMinSpeed", label = "Crash Shake Min", min = 0, max = 160, step = 1 },
		{ key = "cameraCrashShakeMaxSpeed", label = "Crash Shake Max", min = 0, max = 260, step = 5 },
		{ key = "cameraLandingShakeMinSpeed", label = "Landing Shake Min", min = 0, max = 180, step = 1 },
		{ key = "cameraLandingShakeMaxSpeed", label = "Landing Shake Max", min = 0, max = 260, step = 5 },
		{ key = "cameraCrashShakeDuration", label = "Shake Duration", min = 0, max = 2, step = 0.05 },
		{ key = "cameraCrashShakeDistance", label = "Shake Distance", min = 0, max = 8, step = 0.1 },
		{ key = "cameraCrashShakeAngleDegrees", label = "Shake Angle", min = 0, max = 12, step = 0.1 },
		{ key = "cameraCrashShakeFrequency", label = "Shake Frequency", min = 0, max = 80, step = 1 },
		{ key = "cameraCrashShakeCooldown", label = "Shake Cooldown", min = 0, max = 2, step = 0.05 },
		{ key = "cameraBoostShakeIntensity", label = "Boost Shake", min = 0, max = 1, step = 0.01 },
	},

	rampRun = 64,
	rampHeight = 18,
	rampWidth = 44,
	rampThickness = 2,
	stuntPlatformHeight = 3,
	stuntPlatformLength = 100,
	stuntPlatformWidth = 56,
	stuntPlatformGap = 80,
}

return Config
