local DebugTuningConfig = {
	debugPanelEnabled = true,
	debugPanelStudioOnly = true,
	debugTuningProperties = {
		{ key = "carVisualResponsiveness", label = "Cab Visual Follow", min = 0, max = 80, step = 1 },
		{ key = "carVisualSnapDistance", label = "Cab Visual Snap", min = 1, max = 200, step = 5 },
		{ key = "carVisualInterpolationDelay", label = "Cab Visual Delay", min = 0, max = 0.25, step = 0.005 },
		{ key = "carVisualMaxExtrapolationTime", label = "Cab Visual Predict", min = 0, max = 0.25, step = 0.005 },
		{ key = "carModelAssetScale", label = "Cab Model Scale", min = 0.25, max = 3, step = 0.05 },
		{ key = "carBodySpringPitchDegrees", label = "Body Spring Pitch", min = 0, max = 20, step = 0.5 },
		{ key = "carBodySpringRollDegrees", label = "Body Spring Roll", min = 0, max = 16, step = 0.5 },
		{ key = "carBodySpringYawDegrees", label = "Body Spring Yaw", min = 0, max = 8, step = 0.25 },
		{ key = "carBodySpringAccelForFullTilt", label = "Body Spring Accel", min = 10, max = 240, step = 5 },
		{ key = "carBodySpringFrequency", label = "Body Spring Freq", min = 0.5, max = 8, step = 0.1 },
		{ key = "carBodySpringDamping", label = "Body Spring Damp", min = 0.1, max = 2, step = 0.05 },
		{ key = "carAccel", label = "Accel", min = 0, max = 250, step = 5 },
		{ key = "carBrake", label = "Brake", min = 0, max = 300, step = 5 },
		{ key = "carReverseDelay", label = "Reverse Delay", min = 0, max = 1, step = 0.05 },
		{ key = "carReverseStopSpeed", label = "Reverse Stop", min = 0, max = 12, step = 0.25 },
		{ key = "carDrag", label = "Drag", min = 0, max = 120, step = 1 },
		{ key = "carMaxForward", label = "Max Forward", min = 20, max = 320, step = 5 },
		{ key = "carMaxReverse", label = "Max Reverse", min = 0, max = 140, step = 5 },
		{ key = "carTurnRate", label = "Turn Rate", min = 0, max = 8, step = 0.05 },
		{ key = "carMinTurnSpeed", label = "Min Turn Speed", min = 0, max = 60, step = 1 },
		{ key = "carTurnSpeedAtMinSpeed", label = "Turn @ Min Speed", min = 0, max = 2, step = 0.05 },
		{ key = "carTurnSpeedAtMaxSpeed", label = "Turn @ Max Speed", min = 0, max = 2, step = 0.05 },
		{ key = "carGrip", label = "Grip", min = 0, max = 40, step = 0.25 },
		{ key = "carDriftGrip", label = "Drift Grip", min = 0, max = 4, step = 0.01 },
		{ key = "carDriftDrag", label = "Drift Drag", min = 0, max = 80, step = 1 },
		{ key = "carDriftRotationSensitivity", label = "Drift Rotation", min = 0.1, max = 8, step = 0.05 },
		{ key = "carDriftAccelMultiplier", label = "Drift Accel", min = 0, max = 1, step = 0.01 },
		{ key = "carDriftDecel", label = "Drift Decel", min = 0, max = 160, step = 1 },
		{ key = "carDriftSlideForce", label = "Drift Slide", min = 0, max = 120, step = 1 },
		{ key = "carDriftMinSpeed", label = "Drift Min Speed", min = 0, max = 120, step = 1 },
		{ key = "carDriftLeanDegrees", label = "Drift Lean", min = -35, max = 35, step = 1 },
		{ key = "carDriftLeanFullSpeed", label = "Drift Lean Speed", min = 1, max = 220, step = 5 },
		{ key = "carDriftLeanFollow", label = "Drift Lean Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carDriveLeanDegrees", label = "Drive Lean", min = -35, max = 35, step = 1 },
		{ key = "carDriveLeanMinSpeed", label = "Drive Lean Min", min = 0, max = 120, step = 1 },
		{ key = "carDriveLeanFullSpeed", label = "Drive Lean Speed", min = 1, max = 220, step = 5 },
		{ key = "carDriveLeanFollow", label = "Drive Lean Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carDriftBoostChargeTime", label = "Boost Charge", min = 0, max = 3, step = 0.05 },
		{ key = "carDriftBoostWindow", label = "Boost Window", min = 0, max = 4, step = 0.05 },
		{ key = "carDriftBoostImpulse", label = "Boost Impulse", min = 0, max = 100, step = 1 },
		{ key = "carDriftBoostAccel", label = "Boost Accel", min = 0, max = 400, step = 5 },
		{ key = "carDriftBoostDuration", label = "Boost Duration", min = 0, max = 2, step = 0.05 },
		{ key = "carDriftBoostMaxSpeed", label = "Boost Max Speed", min = 20, max = 360, step = 5 },
		{ key = "carCrashBounce", label = "Crash Bounce", min = 0, max = 1, step = 0.01 },
		{ key = "carCrashSlideRetain", label = "Crash Slide", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeMaxAngleDegrees", label = "Wall Scrape Angle", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeSpeedRetain", label = "Wall Scrape Speed", min = 0, max = 1, step = 0.01 },
		{ key = "carWallScrapeDeflectAngleDegrees", label = "Wall Scrape Deflect", min = 0, max = 45, step = 1 },
		{ key = "carWallScrapeMinSpeed", label = "Wall Scrape Min", min = 0, max = 80, step = 1 },
		{ key = "carWallScrapeYawRate", label = "Wall Scrape Turn", min = 0, max = 24, step = 0.5 },
		{ key = "carGravityUp", label = "Gravity Up", min = 20, max = 320, step = 5 },
		{ key = "carGravityDown", label = "Gravity Down", min = 20, max = 520, step = 5 },
		{ key = "carHillAirtimeGraceSeconds", label = "Hill Airtime Grace", min = 0, max = 2, step = 0.01 },
		{ key = "carHillAirtimeMaxGraceSeconds", label = "Hill Airtime Max", min = 0, max = 3, step = 0.01 },
		{ key = "carHillAirtimeSlopeGraceScale", label = "Hill Airtime Slope", min = 0, max = 0.5, step = 0.01 },
		{ key = "carHillAirtimeMinSpeed", label = "Hill Airtime Speed", min = 0, max = 120, step = 1 },
		{ key = "carHillAirtimeMinDownhillPitchDegrees", label = "Hill Airtime Pitch", min = 0, max = 45, step = 1 },
		{ key = "carHillAirtimeCrestGraceSeconds", label = "Crest Airtime Grace", min = 0, max = 2, step = 0.01 },
		{ key = "carHillAirtimeCrestMaxGraceSeconds", label = "Crest Airtime Max", min = 0, max = 3, step = 0.01 },
		{ key = "carHillAirtimeCrestMinUphillPitchDegrees", label = "Crest Uphill Pitch", min = 0, max = 45, step = 1 },
		{ key = "carHillAirtimeCrestMinFlattenDegrees", label = "Crest Flatten", min = 0, max = 45, step = 1 },
		{ key = "carHillAirtimeCrestMinRiseExcess", label = "Crest Rise Excess", min = 0, max = 30, step = 0.5 },
		{ key = "carHillAirtimeCrestMaxGroundRise", label = "Crest Ground Rise", min = 0, max = 6, step = 0.1 },
		{ key = "carHillAirtimeMinGapGrowth", label = "Hill Airtime Gap", min = 0, max = 0.1, step = 0.001 },
		{ key = "carHillAirtimeGapCheckIntervalSeconds", label = "Hill Airtime Check", min = 0.01, max = 0.5, step = 0.01 },
		{ key = "carHillAirtimeGapStallSeconds", label = "Hill Airtime Stall", min = 0, max = 0.5, step = 0.01 },
		{ key = "carHillAirtimeMaxLaunchStepUp", label = "Hill Airtime Step Up", min = 0, max = 2, step = 0.05 },
		{ key = "carGroundSnapDistance", label = "Ground Snap", min = 0, max = 12, step = 0.25 },
		{ key = "carGroundMaxStepUp", label = "Ground Step Up", min = 0, max = 12, step = 0.25 },
		{ key = "carGroundMixedHeightAngleDegrees", label = "Ground Edge Angle", min = 5, max = 75, step = 1 },
		{ key = "carGroundProbeHalfWidth", label = "Probe Width", min = 1, max = 8, step = 0.1 },
		{ key = "carGroundProbeHalfLength", label = "Probe Length", min = 2, max = 10, step = 0.1 },
		{ key = "carFallResetY", label = "Fall Reset Y", min = -500, max = 0, step = 5 },
		{ key = "carFallResetLookbackTime", label = "Fall Reset Lookback", min = 0, max = 3, step = 0.05 },
		{ key = "carFallResetTurnaroundDegrees", label = "Fall Reset Turn", min = 0, max = 360, step = 5 },
		{ key = "carFallResetMinGroundContacts", label = "Fall Reset Contacts", min = 1, max = 4, step = 1 },
		{ key = "carFallResetCooldown", label = "Fall Reset Cooldown", min = 0, max = 3, step = 0.05 },
		{ key = "carPitchFollow", label = "Pitch Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carRollFollow", label = "Roll Follow", min = 0, max = 24, step = 0.5 },
		{ key = "carAirPitchInputDegrees", label = "Air Pitch Rate", min = -180, max = 180, step = 5 },
		{ key = "carAirRollInputDegrees", label = "Air Roll Rate", min = -180, max = 180, step = 5 },
		{ key = "carAirRotationFollow", label = "Air Rotation Follow", min = 0, max = 30, step = 0.5 },
		{ key = "carAirPitchUpGravityMultiplier", label = "Air Nose Up Gravity", min = 0, max = 3, step = 0.05 },
		{ key = "carAirPitchDownGravityMultiplier", label = "Air Nose Down Gravity", min = 0, max = 3, step = 0.05 },
		{ key = "carMaxPitchDegrees", label = "Max Pitch", min = 0, max = 90, step = 1 },
		{ key = "carGroundMaxRollDegrees", label = "Max Roll", min = 0, max = 90, step = 1 },
		{ key = "carLandingBoostImpulse", label = "Landing Boost", min = 0, max = 120, step = 1 },
		{ key = "carLandingBoostMaxSpeed", label = "Landing Boost Max", min = 20, max = 360, step = 5 },
		{ key = "carLandingBoostAlignDegrees", label = "Landing Boost Align", min = 0, max = 35, step = 1 },
		{ key = "carLandingBoostMinAirTime", label = "Landing Boost Air", min = 0, max = 1.5, step = 0.01 },
		{ key = "carBoostWheelieDegrees", label = "Boost Wheelie", min = 0, max = 35, step = 1 },
		{ key = "carBoostWheelieDuration", label = "Boost Wheelie Time", min = 0, max = 2, step = 0.05 },
		{ key = "carBoostWheelieReturnDuration", label = "Wheelie Return Time", min = 0, max = 2, step = 0.05 },
		{ key = "carBoostWheelieFollow", label = "Wheelie Rise Follow", min = 0, max = 40, step = 0.5 },
		{ key = "carLandingBounceMinSpeed", label = "Bounce Min Speed", min = 0, max = 160, step = 1 },
		{ key = "carLandingBounceMaxSpeed", label = "Bounce Max Speed", min = 0, max = 260, step = 5 },
		{ key = "carLandingBounceImpulse", label = "Bounce Impulse", min = 0, max = 60, step = 1 },
		{ key = "carLandingBounceSpring", label = "Bounce Spring", min = 0, max = 180, step = 5 },
		{ key = "carLandingBounceDamping", label = "Bounce Damping", min = 0, max = 50, step = 0.5 },
		{ key = "carLandingBounceMaxOffset", label = "Bounce Max Offset", min = 0, max = 6, step = 0.1 },
		{ key = "passengerActiveCount", label = "Active Count", min = 1, max = 12, step = 1 },
		{ key = "passengerStopRoadEdgeInset", label = "Stop Edge Margin", min = 0, max = 48, step = 1 },
		{ key = "passengerModelHeight", label = "Passenger Height", min = 3, max = 8, step = 0.1 },
		{ key = "passengerGroundLiftLegFraction", label = "Passenger Lift", min = -0.5, max = 1.5, step = 0.05 },
		{ key = "passengerPickupRadius", label = "Pickup Radius", min = 4, max = 80, step = 1 },
		{ key = "passengerDeliveryRadius", label = "Dropoff Radius", min = 4, max = 90, step = 1 },
		{ key = "passengerStoppedSpeed", label = "Board Stop Speed", min = 0, max = 15, step = 0.25 },
		{ key = "passengerBoardingSpeed", label = "Board Speed", min = 1, max = 90, step = 1 },
		{ key = "passengerBoardingCancelDistance", label = "Board Cancel Dist", min = 4, max = 160, step = 1 },
		{ key = "passengerBoardingMaxDoorSurfaceHeight", label = "Board Door Height", min = 0, max = 30, step = 0.5 },
		{ key = "passengerGroundMaxStepUp", label = "Passenger Step Up", min = 0, max = 20, step = 0.5 },
		{ key = "passengerGroundMaxStepDown", label = "Passenger Step Down", min = 0, max = 40, step = 0.5 },
		{ key = "passengerGroundMinNormalY", label = "Passenger Ground Normal", min = 0, max = 1, step = 0.05 },
		{ key = "passengerExitSpeed", label = "Exit Speed", min = 1, max = 90, step = 1 },
		{ key = "passengerModeSwitchCooldown", label = "Mode Cooldown", min = 0, max = 2, step = 0.05 },
		{ key = "passengerDiveMinCabSpeed", label = "Dive Trigger Speed", min = 0, max = 120, step = 1 },
		{ key = "passengerDiveReactionTime", label = "Dive Lookahead Time", min = 0.05, max = 1.5, step = 0.05 },
		{ key = "passengerDiveMaxAheadDistance", label = "Dive Lookahead Max", min = 8, max = 120, step = 2 },
		{ key = "passengerDiveThreatHalfWidth", label = "Dive Threat Width", min = 1, max = 24, step = 0.5 },
		{ key = "passengerDiveSpeed", label = "Dive Speed", min = 20, max = 180, step = 2 },
		{ key = "passengerDiveReturnSpeed", label = "Dive Return Speed", min = 1, max = 80, step = 1 },
		{ key = "passengerDiveArcHeight", label = "Dive Arc Height", min = 0, max = 18, step = 0.5 },
		{ key = "passengerDiveLeanDegrees", label = "Dive Lean", min = 0, max = 120, step = 1 },
		{ key = "passengerDiveRollDegrees", label = "Dive Roll", min = 0, max = 90, step = 1 },
		{ key = "carDamageMinImpactSpeed", label = "Damage Min Impact", min = 0, max = 120, step = 1 },
		{ key = "carDamageImpactSeverityScale", label = "Damage Impact Scale", min = 0, max = 1.5, step = 0.01 },
		{ key = "carDamageForgivenessWindowSeconds", label = "Damage Forgiveness", min = 0, max = 2, step = 0.01 },
		{ key = "carDamageScrapeTickSeconds", label = "Damage Scrape Tick", min = 0.01, max = 1, step = 0.01 },
		{ key = "carDamageSeverityToPointsScale", label = "Damage To Points", min = 0, max = 5, step = 0.05 },
		{ key = "cameraMinSpeed", label = "Camera Min Speed", min = 0, max = 220, step = 5 },
		{ key = "cameraMinDistance", label = "Camera Min Dist", min = 1, max = 100, step = 1 },
		{ key = "cameraMinHeight", label = "Camera Min Height", min = 1, max = 60, step = 0.5 },
		{ key = "cameraMinFov", label = "Camera Min FOV", min = 40, max = 110, step = 1 },
		{ key = "cameraMaxSpeed", label = "Camera Max Speed", min = 0, max = 320, step = 5 },
		{ key = "cameraMaxDistance", label = "Camera Max Dist", min = 1, max = 120, step = 1 },
		{ key = "cameraMaxHeight", label = "Camera Max Height", min = 1, max = 60, step = 0.5 },
		{ key = "cameraMaxFov", label = "Camera Max FOV", min = 40, max = 120, step = 1 },
		{ key = "cameraLookHeight", label = "Camera Look Height", min = 0, max = 20, step = 0.25 },
		{ key = "cameraLookAheadDistance", label = "Camera Look Ahead", min = 0, max = 40, step = 0.5 },
		{ key = "cameraMovementDirectionMinSpeed", label = "Camera Move Dir Speed", min = 0, max = 40, step = 0.5 },
		{ key = "cameraReverseLookDelay", label = "Reverse Look Delay", min = 0, max = 2, step = 0.05 },
		{ key = "cameraYawResponsiveness", label = "Camera Yaw Follow", min = 0, max = 30, step = 0.5 },
		{ key = "cameraTargetResponsiveness", label = "Camera Target Follow", min = 0, max = 40, step = 0.5 },
		{ key = "cameraPositionResponsiveness", label = "Camera Pos Follow", min = 0, max = 40, step = 0.5 },
		{ key = "cameraMaxDeltaTime", label = "Camera Max Dt", min = 0.005, max = 0.2, step = 0.005 },
		{ key = "cameraCrashShakeMinSpeed", label = "Crash Shake Min", min = 0, max = 160, step = 1 },
		{ key = "cameraCrashShakeMaxSpeed", label = "Crash Shake Max", min = 0, max = 260, step = 5 },
		{ key = "cameraLandingShakeMinSpeed", label = "Landing Shake Min", min = 0, max = 180, step = 1 },
		{ key = "cameraLandingShakeMaxSpeed", label = "Landing Shake Max", min = 0, max = 260, step = 5 },
		{ key = "cameraCrashShakeDuration", label = "Shake Duration", min = 0, max = 2, step = 0.05 },
		{ key = "cameraCrashShakeDistance", label = "Shake Distance", min = 0, max = 8, step = 0.1 },
		{ key = "cameraCrashShakeAngleDegrees", label = "Shake Angle", min = 0, max = 12, step = 0.1 },
		{ key = "cameraCrashShakeFrequency", label = "Shake Frequency", min = 0, max = 80, step = 1 },
		{ key = "cameraCrashShakeCooldown", label = "Shake Cooldown", min = 0, max = 2, step = 0.05 },
		{ key = "cameraBoostShakeIntensity", label = "Boost Shake", min = 0, max = 1, step = 0.01 },
	},
}

return DebugTuningConfig
