local FareConfig = {
	passengerFareModeAttribute = "Cab87FareMode",
	passengerFareStatusAttribute = "Cab87FareStatus",
	passengerFareDistanceAttribute = "Cab87FareDistance",
	passengerDestinationAttribute = "Cab87FareDestination",
	passengerFareCompletedAttribute = "Cab87FaresCompleted",
	passengerFareEstimateAttribute = "Cab87FareEstimate",
	passengerFareActiveValueAttribute = "Cab87FareActiveValue",
	passengerFarePayoutAttribute = "Cab87FarePayout",
	passengerFareTimeComponentAttribute = "Cab87FareTimeComponent",
	passengerFareSpeedBonusAttribute = "Cab87FareSpeedBonus",
	passengerFareDamagePenaltyAttribute = "Cab87FareDamagePenalty",
	passengerFareDamageCollisionsAttribute = "Cab87FareDamageCollisions",
	passengerFareDamageSeverityAttribute = "Cab87FareDamageSeverity",
	passengerFareDamagePointsAttribute = "Cab87FareDamagePoints",
	passengerFareResultStatusAttribute = "Cab87FareResultStatus",
	passengerFareDurationAttribute = "Cab87FareDuration",
	passengerFareRouteDistanceAttribute = "Cab87FareRouteDistance",

	fareBaseValue = 10,
	fareDistanceStudsPerUnit = 45,
	fareTimeTargetStudsPerSecond = 32,
	fareTimeBonusMax = 12,
	fareTimePenaltyMax = 12,
	fareSpeedBonusFastThreshold = 1.15,
	fareSpeedBonusPerfectThreshold = 1.45,
	fareSpeedBonusFastValue = 6,
	fareSpeedBonusPerfectValue = 12,
	fareDamagePenaltyPerPoint = 1,
	fareMinimumPayout = 8,
	fareMaximumPayout = 180,
}

return FareConfig
